// Generated by CoffeeScript 1.6.2
/*
  @author Curtis M. Humphrey, Ph.D.
  
  The files adds a KO binding for iScroll 4
      
  Dependence (from global namespace):
    ko - knockoutjs
    iScroll 4 - from http://cubiq.org/iscroll-4
      
  Public API, Fired Events, or Exports
    export on ko as a new binding e.g., data-bind="iscroll4: value"
      where value = 
        update_on: ko observableArray, 
        enable_when: ko observable (true / false)
        parameters.. from iscroll documentation


  Notes:
    element that this binding is on needs to have a specified height
    first child of element needs to have the height that contains all its children as it is the scroller
      - often this means float:left;
*/


(function() {
  var has_iscroll;

  has_iscroll = '__ko_has_iscroll';

  ko.bindingHandlers.iscroll4 = {
    init: function(element, valueAccessor, allBindingsAccessor, viewModel, bindingContext) {
      var Refresh, enable_when, update_on, values, _ref, _ref1;

      Refresh = function() {
        return setTimeout(function() {
          return element[has_iscroll].refresh();
        }, 0);
      };
      values = ko.utils.unwrapObservable(valueAccessor());
      update_on = (_ref = values.update_on) != null ? _ref : false;
      delete values.update_on;
      enable_when = (_ref1 = values.enable_when) != null ? _ref1 : false;
      delete values.enable_when;
      element[has_iscroll] = new iScroll(element, values);
      if (update_on !== false) {
        update_on.subscribe(function(newValue) {
          return Refresh();
        });
      }
      if (enable_when !== false) {
        enable_when.subscribe(function(newValue) {
          if (newValue) {
            return element[has_iscroll].enable();
          } else {
            return element[has_iscroll].disable();
          }
        });
      }
      return Refresh();
    }
  };

}).call(this);
